name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        cmake -B build -DUSE_GETTEXT=ON
        cmake --build build
